baseurl = "https://blog.filovitch.be"
title = "Blog de Filovitch"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Filovitch"
  info = "Magicien des ordinateurs"
  description = "Notes et pensées d'un IT passionné des choses simples"
  keywords = "blog,IT,personal"
  avatarurl = "images/avatar.png"
  gravatar = "j.vandenbroeck@outlook.com"

  since = 2024

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/filovitch"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://x.com/filovitch"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/jonathan-van-den-broeck-a9944523/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss-square fa-2x"
  weight = 4
  url = "/posts/index.xml"

# Menu links
[[menu.main]]
  name = "Maintenant"
  weight = 2
  url  = "now/"
[[menu.main]]
  name = "Articles"
  weight = 3
  url  = "posts/"
[[menu.main]]
  name = "A propos"
  weight = 1
  url = "about/"